/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.util.ArrayList;
import java.util.List;
import Logica.DirectorioTelefonico;

/**
 *
 * @author dannita
 */
public class JFMenuPrincipal extends javax.swing.JFrame {
    public static List<String> listaCiudades;
    public static DirectorioTelefonico directorio;
    /**
     * Creates new form MenuPrincipal
     */
    public JFMenuPrincipal() {
        initComponents();
        JFMenuPrincipal.listaCiudades = new ArrayList<>();
        JFMenuPrincipal.directorio = new DirectorioTelefonico();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDPMenuPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemAgregarCliente = new javax.swing.JMenuItem();
        jMenuItemBuscarCliente = new javax.swing.JMenuItem();
        jMenuItemBorrarCliente = new javax.swing.JMenuItem();
        jMenuDirectorio = new javax.swing.JMenu();
        jMenuCiudades = new javax.swing.JMenu();
        jMenuItemAgregarCiudad = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu principal");

        javax.swing.GroupLayout JDPMenuPrincipalLayout = new javax.swing.GroupLayout(JDPMenuPrincipal);
        JDPMenuPrincipal.setLayout(JDPMenuPrincipalLayout);
        JDPMenuPrincipalLayout.setHorizontalGroup(
            JDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        JDPMenuPrincipalLayout.setVerticalGroup(
            JDPMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        jMenuClientes.setText("Clientes");

        jMenuItemAgregarCliente.setText("Agregar cliente");
        jMenuItemAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemAgregarCliente);

        jMenuItemBuscarCliente.setText("Buscar cliente");
        jMenuItemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBuscarClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemBuscarCliente);

        jMenuItemBorrarCliente.setText("Borrar cliente");
        jMenuItemBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemBorrarCliente);

        jMenuBar1.add(jMenuClientes);

        jMenuDirectorio.setText("Directorio");
        jMenuBar1.add(jMenuDirectorio);

        jMenuCiudades.setText("Ciudades");
        jMenuCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCiudadesActionPerformed(evt);
            }
        });

        jMenuItemAgregarCiudad.setText("Agregar ciudad");
        jMenuItemAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarCiudadActionPerformed(evt);
            }
        });
        jMenuCiudades.add(jMenuItemAgregarCiudad);

        jMenuBar1.add(jMenuCiudades);

        jMenuSalir.setText("Salir");
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDPMenuPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JDPMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCiudadesActionPerformed
       // TODO add your handling code here: 
    }//GEN-LAST:event_jMenuCiudadesActionPerformed

    private void jMenuItemAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarCiudadActionPerformed
        JDPMenuPrincipal.removeAll();
        JDPMenuPrincipal.repaint();
        JIFAgregarCiudad vAgregarCiudad= new JIFAgregarCiudad();
        vAgregarCiudad.setVisible(true);
        JDPMenuPrincipal.add(vAgregarCiudad);
        vAgregarCiudad.toFront();
    }//GEN-LAST:event_jMenuItemAgregarCiudadActionPerformed

    private void jMenuItemAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarClienteActionPerformed
        JDPMenuPrincipal.removeAll();
        JDPMenuPrincipal.repaint();
        JIFAgregarCliente vAgregarCliente = new JIFAgregarCliente();
        vAgregarCliente.setVisible(true);
        JDPMenuPrincipal.add(vAgregarCliente);
        vAgregarCliente.toFront();
    }//GEN-LAST:event_jMenuItemAgregarClienteActionPerformed

    private void jMenuItemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBuscarClienteActionPerformed
        JDPMenuPrincipal.removeAll();
        JDPMenuPrincipal.repaint();
        JIFBuscarCliente vBuscarCliente = new JIFBuscarCliente();
        vBuscarCliente.setVisible(true);
        JDPMenuPrincipal.add(vBuscarCliente);
        vBuscarCliente.toFront();
    }//GEN-LAST:event_jMenuItemBuscarClienteActionPerformed

    private void jMenuItemBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarClienteActionPerformed
        JDPMenuPrincipal.removeAll();
        JDPMenuPrincipal.repaint();
        JIFBorrarCliente vBorrarCliente = new JIFBorrarCliente();
        vBorrarCliente.setVisible(true);
        JDPMenuPrincipal.add(vBorrarCliente);
        vBorrarCliente.toFront();
    }//GEN-LAST:event_jMenuItemBorrarClienteActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDPMenuPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCiudades;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuDirectorio;
    private javax.swing.JMenuItem jMenuItemAgregarCiudad;
    private javax.swing.JMenuItem jMenuItemAgregarCliente;
    private javax.swing.JMenuItem jMenuItemBorrarCliente;
    private javax.swing.JMenuItem jMenuItemBuscarCliente;
    private javax.swing.JMenu jMenuSalir;
    // End of variables declaration//GEN-END:variables
}
