/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Logica.Alumno;
import Logica.Materia;
import java.util.HashSet;

/**
 *
 * @author dannita
 */
public class AppPrincipal extends javax.swing.JFrame {
    public static HashSet<Alumno> listaAlumnos;
    public static HashSet<Materia> listaMaterias;
    
    /**
     * Creates new form Campus
     */
    public AppPrincipal() {
        initComponents();
        listaAlumnos = new HashSet<>();
        listaMaterias = new HashSet<>();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jMenuItemAgregarAlumno = new javax.swing.JMenuItem();
        jMenuItemBorrarAlumno = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemAgregarMateria = new javax.swing.JMenuItem();
        jMenuItemBorrarMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemInscribirAlumno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escritorio");

        escritorio.setName(""); // NOI18N

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jMenuAlumno.setText("Alumnos");
        jMenuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlumnoActionPerformed(evt);
            }
        });

        jMenuItemAgregarAlumno.setText("Agregar alumno");
        jMenuItemAgregarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jMenuItemAgregarAlumno);

        jMenuItemBorrarAlumno.setText("Borrar alumno");
        jMenuItemBorrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jMenuItemBorrarAlumno);

        jMenuBar1.add(jMenuAlumno);

        jMenu2.setText("Materia");

        jMenuItemAgregarMateria.setText("Agregar materia");
        jMenuItemAgregarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemAgregarMateria);

        jMenuItemBorrarMateria.setText("Borrar materia");
        jMenuItemBorrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemBorrarMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Inscripcion");

        jMenuItemInscribirAlumno.setText("Inscribir alumno");
        jMenuItemInscribirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInscribirAlumnoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemInscribirAlumno);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salir");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir del programa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlumnoActionPerformed

    private void jMenuItemAgregarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarAlumnoActionPerformed
        // Comentarios propios
        escritorio.removeAll(); // Este metodo remueve todos InternalFrame y demás componentes para no duplicar ventanas en el DesktopPane.
        escritorio.repaint(); // Limpia el area en donde estaba el componente, es como hacer f5.
        FormularioAlumnos vA = new FormularioAlumnos(); // Instancio.
        vA.setVisible(true); // Hago la ventana visible.
        escritorio.add(vA); // Añado la ventana al escritorio DesktopPane.
        escritorio.moveToFront(vA); // Mueve la ventana al frente, por si había otras internas abiertas. 
    }//GEN-LAST:event_jMenuItemAgregarAlumnoActionPerformed

    private void jMenuItemAgregarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMaterias vM = new FormularioMaterias();
        vM.setVisible(true);
        escritorio.add(vM);
        escritorio.moveToFront(vM);
    }//GEN-LAST:event_jMenuItemAgregarMateriaActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItemInscribirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInscribirAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioInscripciones vI = new FormularioInscripciones();
        vI.setVisible(true);
        escritorio.add(vI);
        escritorio.moveToFront(vI);
    }//GEN-LAST:event_jMenuItemInscribirAlumnoActionPerformed

    private void jMenuItemBorrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumnosBorrar vAB = new FormularioAlumnosBorrar();
        vAB.setVisible(true);
        escritorio.add(vAB);
        escritorio.moveToFront(vAB);
    }//GEN-LAST:event_jMenuItemBorrarAlumnoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemBorrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMateriasBorrar vMB = new FormularioMateriasBorrar();
        vMB.setVisible(true);
        escritorio.add(vMB);
        escritorio.moveToFront(vMB);
    }//GEN-LAST:event_jMenuItemBorrarMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAgregarAlumno;
    private javax.swing.JMenuItem jMenuItemAgregarMateria;
    private javax.swing.JMenuItem jMenuItemBorrarAlumno;
    private javax.swing.JMenuItem jMenuItemBorrarMateria;
    private javax.swing.JMenuItem jMenuItemInscribirAlumno;
    // End of variables declaration//GEN-END:variables
}
