/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaz;

import Logica.Alumno;
import javax.swing.JOptionPane;
import static Interfaz.AppPrincipal.listaAlumnos;

/**
 *
 * @author dannita
 */
public class FormularioAlumnos extends javax.swing.JInternalFrame {
    /**
     * Creates new form VistaAlumnos
     */
    public FormularioAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldLegajoAlumno = new javax.swing.JTextField();
        fieldApellidoAlumno = new javax.swing.JTextField();
        fieldNombreAlumno = new javax.swing.JTextField();
        jButtonGuardarAlumno = new javax.swing.JButton();
        jButtonNuevoAlumno = new javax.swing.JButton();
        jButtonSalirFormAlumno = new javax.swing.JButton();

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario Alumnos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Legajo:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Nombre:");

        fieldLegajoAlumno.setEnabled(false);
        fieldLegajoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLegajoAlumnoActionPerformed(evt);
            }
        });

        fieldApellidoAlumno.setEnabled(false);

        fieldNombreAlumno.setEnabled(false);

        jButtonGuardarAlumno.setText("Guardar");
        jButtonGuardarAlumno.setEnabled(false);
        jButtonGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarAlumnoActionPerformed(evt);
            }
        });

        jButtonNuevoAlumno.setText("Nuevo");
        jButtonNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoAlumnoActionPerformed(evt);
            }
        });

        jButtonSalirFormAlumno.setText("Salir");
        jButtonSalirFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirFormAlumnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(fieldNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldLegajoAlumno)
                                    .addComponent(fieldApellidoAlumno)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButtonGuardarAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonNuevoAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalirFormAlumno)))
                .addGap(32, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldLegajoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldApellidoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldNombreAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardarAlumno)
                    .addComponent(jButtonNuevoAlumno)
                    .addComponent(jButtonSalirFormAlumno))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldLegajoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLegajoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLegajoAlumnoActionPerformed

    private void jButtonNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoAlumnoActionPerformed
        fieldApellidoAlumno.setEnabled(true);
        fieldNombreAlumno.setEnabled(true);
        fieldLegajoAlumno.setEnabled(true);
        jButtonGuardarAlumno.setEnabled(true);
        jButtonNuevoAlumno.setEnabled(false);
    }//GEN-LAST:event_jButtonNuevoAlumnoActionPerformed

    private void jButtonSalirFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirFormAlumnoActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirFormAlumnoActionPerformed

    private void jButtonGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarAlumnoActionPerformed
        String regex = "[a-zA-ZÁÉÍÓÚáéíóúñÑ\\s]+$";
        try {
            if (!fieldNombreAlumno.getText().matches(regex) || !fieldApellidoAlumno.getText().matches(regex) || fieldNombreAlumno.getText().trim().isEmpty() || fieldApellidoAlumno.getText().trim().isEmpty() || fieldLegajoAlumno.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Los datos ingresados no son los requeridos. Intentelo nuevamente.");
                fieldApellidoAlumno.setText("");
                fieldNombreAlumno.setText("");
                fieldLegajoAlumno.setText("");
            } else {
                int legajo = Integer.parseInt(fieldLegajoAlumno.getText());
                Alumno alumno = new Alumno(legajo, fieldApellidoAlumno.getText(), fieldNombreAlumno.getText());
                listaAlumnos.add(alumno);
                JOptionPane.showMessageDialog(this, "Alumno agregado con exito.");
                fieldApellidoAlumno.setText("");
                fieldApellidoAlumno.setEnabled(false);
                fieldNombreAlumno.setText("");
                fieldNombreAlumno.setEnabled(false);
                fieldLegajoAlumno.setText("");
                fieldLegajoAlumno.setEnabled(false);
                jButtonGuardarAlumno.setEnabled(false);
                jButtonNuevoAlumno.setEnabled(true);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Error: El formato de uno de los datos ingresados no coincide con lo requerido.");
            fieldApellidoAlumno.setText("");
            fieldNombreAlumno.setText("");
            fieldLegajoAlumno.setText("");
        }
    }//GEN-LAST:event_jButtonGuardarAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldApellidoAlumno;
    private javax.swing.JTextField fieldLegajoAlumno;
    private javax.swing.JTextField fieldNombreAlumno;
    private javax.swing.JButton jButtonGuardarAlumno;
    private javax.swing.JButton jButtonNuevoAlumno;
    private javax.swing.JButton jButtonSalirFormAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
