/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Interfaz;

import Logica.Materia;
import javax.swing.JOptionPane;
import static Interfaz.AppPrincipal.listaMaterias;

/**
 *
 * @author dannita
 */
public class FormularioMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form formularioMaterias
     */
    public FormularioMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldCodigoMateria = new javax.swing.JTextField();
        fieldNombreMateria = new javax.swing.JTextField();
        fieldAñoMateria = new javax.swing.JTextField();
        jButtonGuardarMateria = new javax.swing.JButton();
        jButtonNuevaMateria = new javax.swing.JButton();
        jButtonSalirFormMateria = new javax.swing.JButton();

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Formulario Materias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Código de la materia: ");

        jLabel3.setText("Nombre de la materia: ");

        jLabel4.setText("Año de la materia: ");

        fieldCodigoMateria.setEnabled(false);
        fieldCodigoMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCodigoMateriaActionPerformed(evt);
            }
        });

        fieldNombreMateria.setEnabled(false);

        fieldAñoMateria.setEnabled(false);

        jButtonGuardarMateria.setText("Guardar");
        jButtonGuardarMateria.setEnabled(false);
        jButtonGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarMateriaActionPerformed(evt);
            }
        });

        jButtonNuevaMateria.setText("Nuevo");
        jButtonNuevaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevaMateriaActionPerformed(evt);
            }
        });

        jButtonSalirFormMateria.setText("Salir");
        jButtonSalirFormMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirFormMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonGuardarMateria)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonNuevaMateria)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonSalirFormMateria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(fieldCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNombreMateria)
                                    .addComponent(fieldAñoMateria))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldAñoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevaMateria)
                    .addComponent(jButtonSalirFormMateria)
                    .addComponent(jButtonGuardarMateria))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCodigoMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCodigoMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCodigoMateriaActionPerformed

    private void jButtonSalirFormMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirFormMateriaActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonSalirFormMateriaActionPerformed

    private void jButtonNuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevaMateriaActionPerformed
        fieldCodigoMateria.setEnabled(true);
        fieldNombreMateria.setEnabled(true);
        fieldAñoMateria.setEnabled(true);
        jButtonGuardarMateria.setEnabled(true);
        jButtonNuevaMateria.setEnabled(false);
    }//GEN-LAST:event_jButtonNuevaMateriaActionPerformed

    private void jButtonGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarMateriaActionPerformed
        String regex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";
        try {
            if (!fieldNombreMateria.getText().matches(regex) || fieldNombreMateria.getText().trim().isEmpty() || fieldCodigoMateria.getText().trim().isEmpty() || fieldAñoMateria.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Uno de los datos ingresados no es lo requerido. Intentelo nuevamente.");
                fieldCodigoMateria.setText("");
                fieldAñoMateria.setText("");
                fieldNombreMateria.setText("");
            } else {
                int codigo = Integer.parseInt(fieldCodigoMateria.getText());
                int año = Integer.parseInt(fieldAñoMateria.getText());
                Materia materia = new Materia(codigo, fieldNombreMateria.getText(), año);
                listaMaterias.add(materia);
                JOptionPane.showMessageDialog(this, "Materia agregada con exito.");
                fieldCodigoMateria.setText("");
                fieldCodigoMateria.setEnabled(false);
                fieldAñoMateria.setText("");
                fieldAñoMateria.setEnabled(false);
                fieldNombreMateria.setText("");
                fieldNombreMateria.setEnabled(false);
                jButtonNuevaMateria.setEnabled(true);
                jButtonGuardarMateria.setEnabled(false);
            }
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Error: El formato de algunos datos ingresados no coinciden con lo requerido.");
            fieldCodigoMateria.setText("");
            fieldNombreMateria.setText("");
            fieldAñoMateria.setText("");
        }
    }//GEN-LAST:event_jButtonGuardarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldAñoMateria;
    private javax.swing.JTextField fieldCodigoMateria;
    private javax.swing.JTextField fieldNombreMateria;
    private javax.swing.JButton jButtonGuardarMateria;
    private javax.swing.JButton jButtonNuevaMateria;
    private javax.swing.JButton jButtonSalirFormMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
